config/routes.rb
Rails.application.routes.draw do

  namespace :admin do 
    resources :users
    resources :prizes
    get     '/archive_prizes', to: "prizes#show_archives", as: 'archive_prizes'
    post '/archive_prize/:id', to: "prizes#archive", as: 'archive_prize'
  end

  resources :users
  resources :prizes
  post  "/redeem/:id", to: "awards#update", as: 'redeem_prize'

  root "sessions#new"

  get     "/login", to: "sessions#new"
  post    "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

end

app/models/award.rb
class Award < ActiveRecord::Base
  belongs_to :user
  belongs_to :prize

  validates :user_id, :prize_id, presence: :true
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  has_many :awards
  has_many :users, through: :awards

  validates :name, :description, :value, presence: true

  has_attached_file :image
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :awards
  has_many :prizes, through: :awards

  validates :points, :role, presence: true
  validates :username, presence: true, uniqueness: true

  has_secure_password

  enum role: ["default", "admin"]

  def to_param
    username
  end

  def admin?
    role == "admin"
  end

  def disabled?
    disable == true
  end

  def not_disabled?
    disable == false
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  def verify_admin
    redirect_to user_path(current_user) unless current_admin?
  end

end

app/controllers/admin/prizes_controller.rb
class Admin::PrizesController < Admin::BaseController

  before_filter :verify_admin

  def new
  end

  def index
    @prizes = Prize.where(archive: false)
  end

  def show
    @prize = Prize.find(params[:id])
  end

  def edit
    @prize = Prize.find(params[:id])
  end

  def update
    prize = Prize.find(params[:id])

    if prize.update(prize_params)
      redirect_to admin_prize_path(prize)
    else
      flash[:errors] = prize.errors.full_messages.join(', ')
      render :edit
    end
  end

  def create
    prize = Prize.new(prize_params)

    if prize.save
      redirect_to admin_prize_path(prize)
    else
      flash[:errors] = prize.errors.full_messages.join(', ')
      render :new
    end
  end

  def archive
    Prize.find(params[:id]).update(archive: true)
    redirect_to admin_prizes_path
  end

  def show_archives
    @archive_prizes =  Prize.where(archive: true)
  end

  private

  def prize_params
    params.require(:prize).permit(:name, :description, :value, :available, :image)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_filter :verify_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:id])
  end

  def update
    user = User.find_by(username: params[:id])

    if user.update(user_params)
      redirect_to admin_user_path(user)
    else
      flash[:errors] = user.errors.full_messages.join(", ")
      redirect_to admin_user_path(user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:points, :role, :disable)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin? 
  end

  def current_user?
    # redirect_to login_path unless session[:id]
  end

end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController

  before_filter :current_user?

  def update
    prize = Prize.find(params[:id])

    points = current_user.points - prize.value

    if points < 0
      flash[:notice] = "You do not have enough points for this prize."
      redirect_to prize_path(prize)
    else
      current_user.update(points: points)
      current_user.prizes << prize
      flash[:notice] = "You have redeemed #{prize.name}!"
      redirect_to user_path(current_user)
    end
  end

end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController

  before_filter :current_user?

  def index
    @prizes = Prize.where(available: true)
  end

  def show
    @prize = Prize.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    session.clear
    render :new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :current_user?

  def new
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/prizes/edit.html.erb
<%= form_for(:prize, url: :admin_prize, method: :put, html: {multipart: true}) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.text_field :value %>
  <%= f.radio_button :available, true %>Yes
  <%= f.radio_button :available, false %>No
  <p>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/prizes/index.html.erb
<% @prizes.each do |prize| %>
  <p>
    <%= prize.name %>
    <%= link_to "edit", edit_admin_prize_path(prize) %>
    <%= link_to "show", admin_prize_path(prize) %>
    <%= button_to "archive", admin_archive_prize_path(prize), confirm: "OK to archive?" %>
  </p>
<% end %>

<%= button_to "New Prize", new_admin_prize_path, method: :get %>
<%= button_to "Archives", admin_archive_prizes_path, method: :get %>

app/views/admin/prizes/new.html.erb
<%= form_for(:prize, url: :admin_prizes, html: {multipart: true}) do |f| %>
  <%= f.text_field :name, placeholder: "name" %>
  <%= f.text_area :description, placeholder: "description" %>
  <%= f.text_field :value, placeholder: "0" %>($)
  <%= f.radio_button :available, true, checked: true %>Yes
  <%= f.radio_button :available, false %>No
  <p>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/prizes/show.html.erb
<h3><%= @prize.name %></h3><br>
<h4>Description</h4>
<%= @prize.description %><br>
<h4>Value</h4>
<%= @prize.value %><br>
<h4>Available</h4>
  <% if @prize.available == true %>
    <%= "YES" %>
  <% else %>
    <%= "NO" %>
  <% end %>
<h4>Picture</h4>
<% if @prize.image_file_name %>
  <p><%= image_tag @prize.image.url %></p>
<% else %>
  <em><p>No Image File</p></em>
<% end %>

app/views/admin/prizes/show_archives.html.erb
<% @archive_prizes.each do |prize| %>
<h4>Name</h4>
<%= prize.name %><br>
<h4>Description</h4>
<%= prize.description %><br>
<h4>Value</h4>
<%= prize.value %><br>
<% end %>

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= user.username %>
    <%= user.points %>
    <%= user.disable %>
    <%= link_to "edit", admin_user_path(user) %>
  </p>
<% end %>

app/views/admin/users/show.html.erb
<%= @user.username %>
<h3>User role: <%= @user.role %> </h3>
<h3>Prizes Awarded</h3>
<% @user.prizes.each do |prize| %>
  <p>
    <%= prize.name %>
    <%= prize.value %>
  </p>
<% end %>

<h3>Update User Points</h3>
<%= form_for(:user, url: :admin_user, method: :put) do |f| %>
  <%= f.text_field :points, value: @user.points  %>
  <%= f.submit %>
<% end %>

<h3>Disable User</h3>
<%= form_for(:user, url: :admin_user, method: :put) do |f| %>
  <%= f.radio_button :disable, true, checked: @user.disabled? %>DISABLED
  <%= f.radio_button :disable, false, checked: @user.not_disabled? %>ACTIVE
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Literail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid nav">
    <% if current_user && current_user.admin? %>
      <%= link_to "Prizes", admin_prizes_path %>
      <%= link_to "Users", admin_users_path %>
    <% end %>
    <% if current_user %>
      <%= link_to "Home", user_path(current_user) %>
    <% end %>
  </div>

  <div class="container-fluid flash">
    <% flash.each do |type,message| %>
      <%= message %>
    <% end %>
  </div>

  <div class="container-fluid">
  <%= yield %>
  </div>
</body>
</html>

app/views/prizes/index.html.erb
<% @prizes.each do |prize| %>
  <p>
    <%= prize.name %>
    <%= link_to "details", prize_path(prize) %>
  </p>
<% end %>

app/views/prizes/show.html.erb
<h3><%= @prize.name %></h3>
<h3><%= @prize.description %></h3>
<h3><%= @prize.value %></h3>
<% if @prize.image_file_name %>
  <h3><%= image_tag @prize.image.url %></h3>
<% else %>
  <em><p>No picture available</p></em>
<% end %>

<%= form_for(:prize, url: :redeem_prize) do |f| %>
  <%= f.submit "Redeem" %>
<% end %>

app/views/users/show.html.erb
<%= button_to "Logout", logout_path, method: :delete %>
<h3>Welcome <%= current_user.username %> </h3>
<p>You have <%= current_user.points %> points</p>

<% if current_user.prizes == [] %>
  <em><p>You have not redeemed any prizes</p></em>
<% else %>
  <p>You have redeemed these prizes!</p>
  <% current_user.prizes.each do |prize| %>
    <%= prize.name %><br>
  <% end %>
<% end %>

<%= link_to "Redeem Prizes", prizes_path %>